insert into izvodjac values (1, 'David Guetta');
insert into izvodjac values (2, 'Skrillex');
insert into izvodjac values (3, 'Hardwell');
insert into izvodjac values (4, 'Boris Brejcha');
insert into izvodjac values (5, 'Enrico Sanguilano');
insert into izvodjac values (6, 'Amelie Lens');
insert into izvodjac values (7, 'Nina Kravitz');
insert into izvodjac values (8, 'Coldplay');
insert into izvodjac values (9, 'The Chainsmokers');
insert into izvodjac values (10, 'Rihanna');
insert into izvodjac values (11, 'Lady Gaga');
insert into izvodjac values (12, 'Eminem');
insert into izvodjac values (13, 'Ariana Grande');
insert into izvodjac values (14, 'Space Motion');
insert into izvodjac values (15, 'Dimitri Vegas & Like Mike');
insert into izvodjac values (16, 'Billie Eilish');
insert into izvodjac values (17, 'The Weeknd');
insert into izvodjac values (18, 'Britney Spears');
insert into izvodjac values (19, 'Ed Sheeran');
insert into izvodjac values (20, 'Bruno Mars');
